# Generated by Django 5.0 on 2023-12-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teaching_Staff', 'Teaching Staff'), ('Non_teaching_Staff', 'Non-teaching Staff')], max_length=20),
        ),
    ]
