# Generated by Django 5.0 on 2023-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_remove_user_id_alter_user_email_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
