# Generated by Django 5.0 on 2023-12-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0008_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
