# Generated by Django 5.0 on 2023-12-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0015_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
