# Generated by Django 5.0 on 2023-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0016_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
