# Generated by Django 5.0 on 2023-12-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0017_complaint_subject_alter_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default='Subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
