# Generated by Django 5.0 on 2023-12-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0018_alter_complaint_subject_alter_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
