# Generated by Django 5.0 on 2023-12-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0019_alter_complaint_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=50),
        ),
    ]
