# Generated by Django 5.0 on 2023-12-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0020_alter_complaint_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
    ]
