# Generated by Django 5.0 on 2024-01-03 18:55

import grievance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0028_remove_responseform_notice_remove_responseform_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotice',
            old_name='notice',
            new_name='notice_content',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='Title', max_length=50, validators=[grievance.models.validate_title]),
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
